RedHatInsights/topological_inventory-persister

Gemfile, lib/topological_inventory/persister/worker.rb
By default, the ruby-kafka was fetching up to 10MB of data,
that could cause spikes in memory, when the queue is full.
We'll fetch only 0.5MB now.
=> Fetch smaller batch from the queue

config/database.dev.yml
we are using `database.dev.yml`s as templates for `database.yml` so let's use same name of DB
as is used in other `topology-` repositories for example [here](https://github.com/ManageIQ/topological_inventory-api/blob/master/config/database.dev.yml#L13)
=> Fix database name in database.dev.yml

lib/topological_inventory/persister/worker.rb, lib/topological_inventory/persister/workflow.rb, spec/persister/collections_spec.rb, spec/persister/mark_and_sweep_spec.rb, spec/persister/worker_spec.rb
Each message will contain primary keys of created, deleted or
changed entities for the batch persistor persisted.
=> Stream graph refresh output to kafka

Dockerfile, docker-assets/entrypoint, docker-assets/run_persister
This allows us to share environment variables in a sane way between
the CMD and users who may get a separate console session into a
running container.
This also provides a place for us to put the definition of
DATABASE_URL as it won't live in the database secret in production
This should be merged with ManageIQ/topological_inventory-deploy#45
=> Use the entrypoint script to set env vars and run_persister in CMD

Dockerfile, Gemfile, lib/topological_inventory/persister/metrics.rb, lib/topological_inventory/persister/worker.rb, spec/persister/metrics_spec.rb
I'm running the prometheus exporter service in the same process here.
This gives us information about the local ruby process and also allows us to run the metrics server in test, dev, and production in the same way.
@Ladas let me know what you think about the metrics I'm collecting in this first pass. Feel free to add more in a follow-up, but I want to know if you think these will be useful.
=> Add metrics

lib/topological_inventory/persister/workflow.rb
It was removed in inventory_refresh
Depends on:
=> Remove saver_strategy option

lib/topological_inventory/persister/worker.rb, spec/persister/refresh_worker_helper.rb, spec/persister/worker_spec.rb
subscribe_messages uses ruby-kafka each_batch, while
subscribe_topic uses each_message. There is something wrong,
probably with offset commit, in the each_batch. At scale of
200k - 1.2M records tested, almost 1 third of messages was being
dropped or skipped.
Switching to each_message for now, until we figure out what is
causing the each_batch issues. The implementation of each_message
seems to work without problems.
=> subscribe_messages has serious issues

lib/topological_inventory/persister/workflow.rb, spec/persister/mark_and_sweep_spec.rb
Using this instead of record.update or record.update_attributes, because the queries are firing several Exists queries on Source, for some reason. We don't need to check for exists. If it doesn't exist the foreign key constraint will be fired.
Depends on:
=> Remove extra queries to source related tables

bin/topological_inventory-persister, lib/topological_inventory/persister/metrics.rb, lib/topological_inventory/persister/worker.rb, spec/persister/refresh_worker_helper.rb, spec/persister/worker_spec.rb
Metrics port is configurable by  `ENV["METRICS_PORT"]`. Defaults to 9394
Port 0 disables metrics
=> Metrics port as an argument

Gemfile
Because dependency from core moved from Gemfile to gemspec
=> Removing inventory_refresh from Gemfile

lib/tasks/openapi_generate.rake
Default is true based on openapi 3.2 spec, but we want a strict
check, not allowing additionalProperties.
=> Generate additionalProperties false

lib/tasks/openapi_generate.rake
source_type name is needed for creating Source with first payload from CFME (through **insights-upload** svc -> **topological-inventory-sync/inventory-upload-worker**)
=> Added source_type to schema

lib/topological_inventory/persister/exception.rb, lib/topological_inventory/persister/worker.rb
Log exception as one record so it's more readable in kibana
and log uknown source_uid as warn, since that can happen
when we delete a source and we still have items in a queue.
=> Cleanup exception handling

lib/tasks/openapi_generate.rake
OpenAPI Generators 4.1+ cannot generate client by JSON generated by `openapi:generate` rake task. 
It fails with validation error: `-attribute components.schemas.Inventory.items is missing`
Regarding to OpenAPI specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
**items MUST be present if the type is array**.
---
- ingress-api: https://github.com/ManageIQ/topological_inventory-ingress_api/pull/69
- ingress-api-client: https://github.com/ManageIQ/topological_inventory-ingress_api-client-ruby/pull/57
=> Openapi array must have items definition

lib/topological_inventory/persister/workflow.rb
`ems_id` is probably forgotten there from ManageIQ
=> Remove old 'ems_id' attribute

lib/tasks/openapi_generate.rake, lib/topological_inventory/persister/workflow.rb
**Issue**: #52 
1) Links from data to RefreshStatePart moved from core: https://github.com/RedHatInsights/topological_inventory-core/pull/186 (#183)
2) Exclude relations from openapi generator
3) Saving refresh timestamps:
* refresh_state_part_collected_at
* refresh_state_part_sent_at
* refresh_state_started_at
* refresh_state_sent_at
* ingress_api_sent_at
* persister_started_at [core]
* persister_finished_at [core]
---
=> Inventory refresh tracking

Gemfile, lib/topological_inventory/persister/workflow.rb
**Issue** https://github.com/RedHatInsights/topological_inventory-ansible_tower/issues/83
Tasks were updated through Topological API, which published Kafka event. 
Catalog update depends on this event so it has to be published from persister too
---
=> Publishing updated Tasks in Kafka

lib/topological_inventory/persister/worker.rb
`client_ref` is consumer's unique ID, so it should be unique.
I didn't find `group_ref`, it seems redundant
=> Unique Kafka's client_ref

Gemfile, lib/topological_inventory/persister/workflow.rb
**Issue** https://github.com/RedHatInsights/topological_inventory-persister/issues/58
Insights::API::Common::Request.current_forwardable is saved in Task instead of x-rh-insights-request-id. To be able to resend it through Kafka in persister
---
- **requires** RubyGems v1.1.4
=> Publish forwardable headers in Task.update

lib/tasks/openapi_generate.rake, spec/openapi_generator_spec.rb
`InventoryCollection` without model_class can't be processed by openapi generator's task. 
Currently failing for `:service_instance_tasks`
=> Fix of rake task openapi:generate

lib/tasks/openapi_generate.rake, lib/topological_inventory/persister/metrics.rb, lib/topological_inventory/persister/worker.rb, spec/persister/worker_spec.rb
**Issue**: https://github.com/RedHatInsights/topological_inventory-persister/issues/66
defaulting to 60 minutes.
e2e-deploy: https://github.com/RedHatInsights/e2e-deploy/pull/2089
\# TODO:
=> Skip Inventories that were sent more than ENV['PERSISTER_TIMEOUT'] ago

spec/persister/refresh_worker_helper.rb
This will (hopefully) prevent the intermittent spec failures we see every so often on this repo.
=> Set spec port to 0 everywhere we do not need the metrics server

lib/topological_inventory/persister/workflow.rb, spec/persister/collections_spec.rb, spec/persister/mark_and_sweep_spec.rb
Persister is sending all changes to persister-output-stream topic. 
But nobody except host-inventory-sync service is using it (checked on CI's kafka lag), so we are creating huge useless streaming
---
[TPINVTRY-1044](https://projects.engineering.redhat.com/browse/TPINVTRY-1044)
=> Reduce output-stream payloads only to VMS

lib/topological_inventory/persister/worker.rb
https://issues.redhat.com/browse/RHCLOUD-9485
Simple PR to add a heartbeat touch after message process. I would use the `providers-common` class - but it doesn't quite make sense to pull in that gem for something that just runs `FileUtils.touch`
=> Add heartbeat check after message process

lib/topological_inventory/persister/metrics.rb, lib/topological_inventory/persister/worker.rb, lib/topological_inventory/persister/workflow.rb, spec/persister/metrics_spec.rb
**Issue** https://github.com/RedHatInsights/topological_inventory-api/issues/320
Labels extension to current metrics `topological_inventory_persister_`:
- messages_total
- message_process_seconds
---
[RHCLOUD-9943](https://issues.redhat.com/browse/RHCLOUD-9943)
=> Custom metrics
